name: Greeting
on: push        # when it will be trigger
jobs: 
    greet:          #greet ---< name of job
        runs-on: ubuntu-latest   # remote machine runner https://github.com/actions/runner-images
        steps:  
            - name: "Echo value"
              run: |
                echo "Echo Github value....."
                 echo '${{ toJson(github) }}'  # getting the current Giihub Values
                 echo ""Cloning the repo......
               
                  git clone https://github.com/${{ github.repository }}.git  #cloning the currebt repo